version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: umbrel-store-plus-wireguard_server_1
      APP_PORT: 51820
    
  server:
    image: weejewel/wg-easy:7
    environment:
      WG_HOST: 0.0.0.0
      PASSWORD: wireguard
      WG_PORT: 51820
      #WG_DEFAULT_DNS: 1.1.1.1
      WG_PERSISTENT_KEEPALIVE: 0
      WG_MTU: null
    ports:
      - target: 51820
        published: 51820
        protocol: udp
      - target: 51821
        published: 51821
        protocol: tcp
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/wireguard/
        target: /etc/wireguard
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1